### ISSUE TITLE
how to use and how is running performance

### ISSUE THREAD

**Issue by dannyshenl** [sam987883/TypeCache#1]
I want to use this reflection methods
```
propertyInfo.GetValue()
propertyInfo.SetValue()
and so on...
```
but bad performance.
can this framework solve performance problems？
thanks for your answer

**Comment by sam987883** [comment]
Yes it can.  TypeCache provides alternatives to `propertyInfo.GetValue()` and `propertyInfo.SetValue(...)`.
For example, to accomplish the same thing with the TypeCache- you can do the following:

```
using TypeCache;

class Customer
{
    public string FirstName { get; set; }
}

var customer = new Customer();

// Get the property value
var firstName = TypeOf<Customer>.Properties["FirstName"].GetValue(customer);

// Set the property value
firstName = "Samuel";
TypeOf<Customer>.Properties["FirstName"].SetValue(customer, firstName);
```

Or, if the `Customer` type is not known at compile time:

```
using TypeCache.Reflection.Extensions;

// Get the property value
var firstName = customer.GetTypeMember().Properties["FirstName"].GetValue(customer);

// Set the property value
firstName = "Samuel";
customer.GetTypeMember().Properties["FirstName"].SetValue(customer, firstName);
```

Behind the scenes the code to get and set the property value is getting built, compiled and cached at runtime.  There is a slight performance hit for the initial build and compiling of the code.  However all subsequent calls to the same property will have no lag in performance and will be almost as fast as calling the property directly in code.

I hope this answers your question.  There are also similar facilities for accessing field values, events, and even dynamically invoking methods with similar performance enhancements.

Thank you

-sam987883

NuGet package is available here: https://www.nuget.org/packages/TypeCache

**Comment by dannyshenl** [comment]
Yes！ Very useful！I'll quote it into my code. Look forward to its follow-up performance.
Sam Thanks for your help.Thank you very much.
